# Generated by Django 5.0.1 on 2024-02-26 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.CharField(choices=[('documentation', 'documentation'), ('blockbuster', 'blockbuster'), ('comedy', 'comedy'), ('action', 'action'), ('drama', 'drama'), ('sitcom', 'sitcom')], max_length=20)),
                ('actors', models.CharField(max_length=20)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
    ]
