# Generated by Django 5.0.1 on 2024-03-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='actors',
            field=models.CharField(max_length=100),
        ),
    ]
