# Generated by Django 5.0.1 on 2024-02-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='regie',
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('documentation', 'documentation'), ('blockbuster', 'blockbuster'), ('comedy', 'comedy'), ('action', 'action'), ('drama', 'drama'), ('sitcom', 'sitcom')], max_length=20),
        ),
    ]
