# Generated by Django 5.0.1 on 2025-05-26 15:01

import datetime
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.CharField(choices=[('documentation', 'documentation'), ('blockbuster', 'blockbuster'), ('comedy', 'comedy'), ('action', 'action'), ('drama', 'drama'), ('sitcom', 'sitcom')], max_length=20)),
                ('actors', models.CharField(max_length=100)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[500, None], upload_to='thumbnails')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='videos.video')),
            ],
        ),
    ]
